/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface SudokuGrid {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLSudokuGridElement extends Components.SudokuGrid, HTMLStencilElement {
    }
    var HTMLSudokuGridElement: {
        prototype: HTMLSudokuGridElement;
        new (): HTMLSudokuGridElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "sudoku-grid": HTMLSudokuGridElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface SudokuGrid {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "sudoku-grid": SudokuGrid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "sudoku-grid": LocalJSX.SudokuGrid & JSXBase.HTMLAttributes<HTMLSudokuGridElement>;
        }
    }
}
